spring:
  # H2 ??
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: test
    password: test

  # Hibernate ??
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openapi:
  kakao:
    url: https://dapi.kakao.com
    authorization: 8e7f55c506ab79f8c4fccaf83e98cd3a

  naver:
    url: https://openapi.naver.com
    client-id: 6Rmw7TW1rzYabiTVQXbj
    client-secret: tLj1GCPMdC